### ISSUE TITLE
IsOpen property won't change when use CloseDialogCommand and CloseOnClickAway to close dialog

### ISSUE THREAD

**Issue by SinoAHpx** [AvaloniaUtils/DialogHost.Avalonia#10]

**Comment by SinoAHpx** [comment]
Actually it's default binding mode is not TwoWay

**Comment by SKProCH** [comment]
Hello, @SinoAHpx 

This gif recorded on the latest commit of `main` branch.
Firstly i demonstrate closing with CloseOnClickAway, in secondly i demonstrate closing via button, that executes CloseDialogCommand.
![dafa2b20-7dbf-4343-bef4-d1f6dc57ef39](https://user-images.githubusercontent.com/29896317/183656597-2b38f3cc-1da6-40df-bdc0-6d721862706f.gif)

Please provide relevant repro info and then feel free to reopen issue.
