### ISSUE TITLE
The application crashes after the keyboard is output and clicking on the View closure

### ISSUE THREAD

**Issue by DenisT90** [AvaloniaUtils/DialogHost.Avalonia#12]
Actions:
1) Add in View TextBox and Button with CloseDialogCommand
2) Run application in Android
3) Show View
4) Click in the text box, the android keyboard appears on the screen
5) Click to close Button
6) We see that the application has terminated with an error

**Comment by SKProCH** [comment]
Hello, @DenisT90 

Can you provide error details (error message and stacktrace) and minimum reproduceable example please?  
I'll try to look soon.

**Comment by DenisT90** [comment]
https://github.com/DenisT90/AvaloniaDialogHostBugWithKeyboard
I created repo for you)

**Comment by SKProCH** [comment]
Seems like this is an Avalonia bug. I've updated Avalonia to 11.0.0-preview3 and seems all working fine now.

**Comment by DenisT90** [comment]
> Seems like this is an Avalonia bug. I've updated Avalonia to 11.0.0-preview3 and seems all working fine now.

How you updated it?
I Changed file Directory.Build.Props to:
```
<Project>
  <PropertyGroup>
    <AvaloniaVersion>11.0.0-preview3</AvaloniaVersion>
  </PropertyGroup>
</Project>
```
And in Android Project MainActivity.cs to:
```
    public class MainActivity : AvaloniaMainActivity
    {
    }
```

After that, I started android, it crashes

**Comment by SKProCH** [comment]
I've created a pull request for you: https://github.com/DenisT90/AvaloniaDialogHostBugWithKeyboard/pull/1
