### ISSUE TITLE
 AlignmentDialogPopupPositioner margin doesn't work when align top left corner

### ISSUE THREAD

**Issue by kevin100702** [AvaloniaUtils/DialogHost.Avalonia#17]
```xml
<!-- It's fine -->
<!--<dialogHostAvalonia:DialogHost.PopupPositioner>
	<positioners:AlignmentDialogPopupPositioner VerticalAlignment="Bottom" HorizontalAlignment="Right" Margin="20"/>
</dialogHostAvalonia:DialogHost.PopupPositioner>-->
			
<dialogHostAvalonia:DialogHost.PopupPositioner>
	<positioners:AlignmentDialogPopupPositioner VerticalAlignment="Top" HorizontalAlignment="Left" Margin="20"/>
</dialogHostAvalonia:DialogHost.PopupPositioner>
```
![image](https://user-images.githubusercontent.com/12688812/206942941-9c24c84b-9dcf-431b-872a-3acd91a9d16e.png)

#16 

The Margin property doesn't work when I try to align the upper left corner, so I forked the latest code and tried it out and found that everything works fine when aligning the small right corner, but not when aligning to the upper left corner. thanks

**Comment by SKProCH** [comment]
Hello, @kevin100702 

You can use `0.7.0-preview2` version, where your problem has been fixed. If not - feel free to reopen issue.
