### ISSUE TITLE
Popup spawn in the wrong place when he is inside of a Viewbox

### ISSUE THREAD

**Issue by SergeyV17** [AvaloniaUtils/DialogHost.Avalonia#2]
**Describe**
If DialogHost control inside of a ViewBox control and if after running the app resize window along two axes(x,y), then popup will spawn in the wrong place (not in a center of the parent conrol). By default, without resizing popup spawns in center of the parent conrol.

Perhaps this behavior is correct?

**Expected behavior**
After resizing the window, popup will spawns in the center of a parent conrol.

**Details**
![ViewboxIssue](https://user-images.githubusercontent.com/57860550/122668356-f9541b00-d1fa-11eb-8c46-96d5cc455b99.gif)

If you override the OverlayLayer control (add HorizontalAlignment=Center, VerticalAlignment=Center, as showed below, then problem is solved:
![image](https://user-images.githubusercontent.com/57860550/122668468-87300600-d1fb-11eb-954d-f54d30b02986.png)

**Repro**
https://github.com/SergeyV17/DialogHostViewBoxIssueRepro

**Comment by SKProCH** [comment]
Sorry for the long answer.

I will try to take the time and fix it soon.

**Comment by SKProCH** [comment]
Fixed in v0.2.2
