### ISSUE TITLE
Usage with MvvmDialogs

### ISSUE THREAD

**Issue by mysteryx93** [AvaloniaUtils/DialogHost.Avalonia#24]
DialogHost can now be used via MvvmDialogs. I updated the documentation here
https://github.com/mysteryx93/HanumanInstitute.MvvmDialogs/#avaloniadialoghost

Perhaps you could update your documentation to mention the alternative usage?

The new package is not yet released; still remains [this issue](https://github.com/AvaloniaUtils/DialogHost.Avalonia/issues/22) to solve first.

If you see DialogHost features or properties that should be added, let me know.

**Comment by SKProCH** [comment]
Done! 
If you want to customize text - feel free to reopen issue.

**Comment by mysteryx93** [comment]
Perhaps you could say

"Alternative Syntax

HanumanInstitute.MvvmDialogs allows the use of MVVM design in a simplified way, with support for DialogHost. If you opt for that syntax, you do not need most of the documentation below, and the DialogHost container is injected automatically at runtime.

**Comment by SKProCH** [comment]
Updated!
