### ISSUE TITLE
Dialog is still present in the visual tree after second opening

### ISSUE THREAD

**Issue by alessandrofrancesconi** [AvaloniaUtils/DialogHost.Avalonia#30]
I'm seeing a strange behavior using `DialogHost.Avalonia 0.7.1` + `Avalonia 11.0.0-preview6` ([cross platform solution](https://docs.avaloniaui.net/tutorials/developing-for-mobile/create-a-cross-platform-solution)). 

Basically if one open a dialog, then closes it, then opens it again, then closes it, the dialog's content remains present in the main visual tree.

I've prepared a sample application to show it (please test the Desktop or Android project) [DialogHostTest.zip](https://github.com/AvaloniaUtils/DialogHost.Avalonia/files/11292602/DialogHostTest.zip)

Also a video of the issue: https://we.tl/t-zLkYAVr5cH

**Comment by SKProCH** [comment]
Wow, there is a surprise, that animations with fill mode `Forward` or `Both` will set last values with priority `Local`, so it can't be overridden in any styles way
