### ISSUE TITLE
Bug when starting and running under net framework 4.7.2

### ISSUE THREAD

**Issue by doubleright** [AvaloniaUtils/DialogHost.Avalonia#39]
在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   在 System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   在 System.Reactive.Disposables.CompositeDisposable.ToList(IEnumerable`1 disposables)
   在 System.Reactive.Disposables.CompositeDisposable..ctor(IEnumerable`1 disposables)
   在 DialogHostAvalonia.Utilities.MultiDynamicResourceExtension.MultiDynamicResourceObservable..ctor(IEnumerable`1 observables, Object defaultValue)
   在 DialogHostAvalonia.Utilities.MultiDynamicResourceExtension.Avalonia.Data.IBinding.Initiate(AvaloniaObject target, AvaloniaProperty targetProperty, Object anchor, Boolean enableDataValidation)
   在 Avalonia.Styling.Setter.SetBinding(StyleInstance instance, AvaloniaObject target, IBinding binding)
   在 Avalonia.Styling.Setter.Instance(IStyleInstance instance, StyledElement target)
   在 Avalonia.Styling.StyleBase.Attach(StyledElement target, IStyleActivator activator, FrameType type)
   在 Avalonia.Styling.ControlTheme.TryAttach(StyledElement target, FrameType type)
   在 Avalonia.StyledElement.ApplyControlTheme(ControlTheme theme, FrameType type)
   在 Avalonia.StyledElement.ApplyControlTheme()
   在 Avalonia.StyledElement.ApplyStyling()
   在 Avalonia.StyledElement.EndInit()

**Comment by SKProCH** [comment]
@doubleright to be honest I can't properly setup a net framework project with Avalonia. Please, provide an minimal reproduceable example.

**Comment by doubleright** [comment]
<Grid>
....
 <Grid Grid.Row="0" Grid.RowSpan="2">
     <dialogHost:DialogHost Identifier="demo1" />
     <dialogHost:DialogHost Identifier="demo2" />
     <dialogHost:DialogHost Identifier="demo3" />
 </Grid>
</Grid>

**Comment by doubleright** [comment]
`  <Grid Grid.Row="0" Grid.RowSpan="2">
      <dialogHost:DialogHost Identifier="demo1" />
      <dialogHost:DialogHost Identifier="demo2" />
      <dialogHost:DialogHost Identifier="demo3" />
      <dialogHost:DialogHost Identifier="demo4" />
....
  </Grid>`

@SKProCH like this xaml

**Comment by SKProCH** [comment]
Still can't setup an Avalonia project what runs on net framework 4.7.2. Can you provide a minimal reproduceable example project (via zip file or github repo) that i can launch to debug this?
