### ISSUE TITLE
Compatibility with Avalonia 11.1?

### ISSUE THREAD

**Issue by Numpsy** [AvaloniaUtils/DialogHost.Avalonia#48]
Hi,

While testing with https://github.com/danipen/TextMateSharp/issues/57#issuecomment-2037832212 in the Avalonia 11.1 previews, I noticed that an about box using DialogHost.Avalonia didn't work correctly - the dialog appeared but didn't disappear when closed, just hung about over the top of the background.

As a test I tried updating the demo application from this repository to the Avalonia 11.1 Beta 1 release and saw there are problems there as well
![dh](https://github.com/AvaloniaUtils/DialogHost.Avalonia/assets/1178570/076bb3dd-eaf6-4471-8685-847099547fac)

There are also some warnings in the debugger output:
```
[Binding]An error occurred binding 'OverlayBackground' to '': 'Could not convert 'DialogHostDemo.ViewModels.MainWindowViewModel' (DialogHostDemo.ViewModels.MainWindowViewModel) to 'Avalonia.Media.IBrush'.' (DialogHost #25747420)
[Binding]An error occurred binding 'Background' to '': 'Could not convert 'DialogHostDemo.ViewModels.MainWindowViewModel' (DialogHostDemo.ViewModels.MainWindowViewModel) to 'Avalonia.Media.IBrush'.' (DialogHost #25747420)
```

Thanks.

**Comment by SKProCH** [comment]
So, currently seems like my custom binding for getting colors from different themes doesn't work with updated binding system from avalonia 11.1.

As for workaround you can set values to this properties (`Background`, `OverlayBackground`) by youself.

I've currently trying to figure out how to adapt to new avalonia binding system.

**Comment by SKProCH** [comment]
Details can found here: https://github.com/AvaloniaUI/Avalonia/issues/15270

**Comment by Numpsy** [comment]
Thanks, my own application is working now with the new update.
