### ISSUE TITLE
DialogHostStyle.SetBorderThickness throws System.ArgumentException

### ISSUE THREAD

**Issue by ExLuzZziVo** [AvaloniaUtils/DialogHost.Avalonia#52]
Setting BorderThickness using `DialogHostStyle.SetBorderThickness` method throws a `System.ArgumentException`. This is because the type of the `value` argument must be `Thickness` not double.

**Steps to reproduce:**
```csharp
var dialogContent = new DialogContent();

DialogHost.Show(dialogContent, (o, args) =>
{
    if (o is DialogHost dialogHost)
    {
        DialogHostStyle.SetBorderThickness(dialogHost, 10);
    }
}, (o, args) =>
{
    //    
});
```

**Exception details:**
```
System.ArgumentException: Invalid value for Property 'BorderThickness': '10' (System.Double)
   at Avalonia.StyledProperty`1.ShouldSetValue(AvaloniaObject target, Object value, TValue& converted)
   at Avalonia.StyledProperty`1.RouteSetValue(AvaloniaObject target, Object value, BindingPriority priority)
   at Avalonia.AvaloniaObject.SetValue(AvaloniaProperty property, Object value, BindingPriority priority)
   at DialogHostAvalonia.DialogHostStyle.SetBorderThickness(DialogHost element, Double value)
```

**This works:**
```csharp
dialogHost.SetValue(DialogHostStyle.BorderThicknessProperty, (object) new Thickness(10));
```

**Comment by SKProCH** [comment]
Hello, @ExLuzZziVo 

Method `void SetBorderThickness(DialogHost element, Thickness value)` already accept only thickness as a value, I can't pass number:

![image](https://github.com/AvaloniaUtils/DialogHost.Avalonia/assets/29896317/0f6c281e-8f6e-43ab-a471-ab6015a204e4)

**Comment by ExLuzZziVo** [comment]
Hi, @SKProCH

I'm using version 0.7.7 from nuget and this method accepts double:
![2024-05-31 150721](https://github.com/AvaloniaUtils/DialogHost.Avalonia/assets/46676089/3ffd5e40-724e-4789-a50f-f7965c1d127d)

**Comment by SKProCH** [comment]
Oh, I see. There is probably an issue with releases. I should rewrite the release process to handle this easily.

**Comment by SKProCH** [comment]
Fixed in last release
