### ISSUE TITLE
DialogHost display error

### ISSUE THREAD

**Issue by SinoAHpx** [AvaloniaUtils/DialogHost.Avalonia#59]
3.7.2 / 11.1.1 / Windows 11 23H2 Pro
![image](https://github.com/user-attachments/assets/f1a69049-79b1-4a7a-af56-916d5cf08451)
DialogHost seems to be transparent in the case, which is unwanted.
```xml
<dialogHostAvalonia:DialogHost CloseOnClickAway="True">
    <dialogHostAvalonia:DialogHost.Content>
        <Carousel/>
    </dialogHostAvalonia:DialogHost.Content>
</dialogHostAvalonia:DialogHost>
```
The DialogHost is set in MainView, inside there's a Carousel, which will be dynamically changed.
The code used to open the DialogHost:
```cs
await DialogHost.Show(new AddAccountDialog());
```
The `AddAccountDialog` is a usercontrol.

**Comment by Numpsy** [comment]
If the ```11.1.1``` is the Avalonia version, that looks sort of like the issue I had in #48?

**Comment by SKProCH** [comment]
Yeah, likely this is a continuation from that issue.

**Comment by Numpsy** [comment]
fwiw, my case is working ok with the Avalonia 11.1.1 release and the ```0.8.0-avalonia11dot1-3``` preview release of DialogHost

**Comment by SKProCH** [comment]
With the Material.Avalonia styles? (And without Fluent included)

**Comment by Numpsy** [comment]
Ah, no, I'm just using the Fluent theme.

**Comment by Coloryr** [comment]
`Avalonia 11.1` Change something and BG is gone.

**Comment by Numpsy** [comment]
I just tried updating DialogHost from ```0.8.0-avalonia11dot1-3``` to ```0.8.0```, and now it's back to seeing the issue from #48

**Comment by SKProCH** [comment]
Probably I've messed up with branching, i'll take a look.

**Comment by SKProCH** [comment]
Should be fine with v0.8.1. If not - reopen the issue.

**Comment by Numpsy** [comment]
Looks ok now, thanks
