### ISSUE TITLE
How to set DisableOpeningAnimation to true

### ISSUE THREAD

**Issue by ngai6666** [AvaloniaUtils/DialogHost.Avalonia#6]
Looks like the version 0.3.1 doesn't include the latest code, so that DisableOpeningAnimation property is not availiable.

**Comment by SKProCH** [comment]
Hello, @ngai6666 

Apparently yes. I thought about adding more changes and then releasing a version, but due to the huge tasks object at work, I couldn't do it.

I will release a version with these changes soon. Thanks.

**Comment by ngai6666** [comment]
@SKProCH  
That's great. I can wait for it.
Thanks

**Comment by SKProCH** [comment]
Hello, @ngai6666 

I published a version v0.4.0

**Comment by ngai6666** [comment]
Hi @SKProCH 
It works great.
