### ISSUE TITLE
How to make the dialog bigger?

### ISSUE THREAD

**Issue by amp64** [AvaloniaUtils/DialogHost.Avalonia#64]
How do I make the dialog bigger? (This is on iOS)

```
	<dialogHostAvalonia:DialogHost x:Name="DialogHost" DialogMargin="4" IsOpen="{Binding VolumePopupOpen}">
		<dialogHostAvalonia:DialogHost.DialogContent>
			<views:GroupVolumeView DataContext="{Binding CurrentZone}"
								   HorizontalAlignment="Stretch" VerticalAlignment="Stretch"/>
		</dialogHostAvalonia:DialogHost.DialogContent>

```

DialogMargin has no apparent affect. See screenshot:
![20240905_234928000_iOS](https://github.com/user-attachments/assets/8b72e267-924d-4bcc-ad72-69b06b299291)

**Comment by SKProCH** [comment]
Hello, @amp64 

Set up the Height and Width property of your dialog view or use custom positioner to change the placement rules of dialog content.

**Comment by amp64** [comment]
Thank you! This was my solution:
```

    private class DialogPopupPositioner : IDialogPopupPositioner
    {
        public Rect Update(Size anchorRectangle, Size size)
        {
            double margin = 12;
            Rect posn = new Rect(0, 0, anchorRectangle.Width, anchorRectangle.Height);
            return posn.Inflate(-margin);
        }
    }

```

**Comment by SKProCH** [comment]
Actually you don't need to implement a _custom_ positioner by yourself, cuz you can try  AlignmentDialogPopupPositioner, it should fit all your needs
