### ISSUE TITLE
MultiDynamicResourceObservable not getting released when DialogHost is removed

### ISSUE THREAD

**Issue by MaxwellDAssistek** [AvaloniaUtils/DialogHost.Avalonia#65]
Hello,

I am working on an application that has plugins that contain Avalonia controls. One of those plugins contains a DialogHost.

The problem that I am encountering is that I am unable to get the plugin unloaded because MultiDynamicResourceObservable is holding observables, which causes it to never get garbage collected as shown in dotMemory:

![image](https://github.com/user-attachments/assets/6e0e4a9e-af56-401c-abdf-fc122d1b1df4)

Is there a way to get those observables released?

**Comment by SKProCH** [comment]
Hello. So, is it isn't released even if DialogHost is removed from the window? Or you don't remove the DialogHost, but resource observable holds the resources which should be released since it is unused?

**Comment by MaxwellDAssistek** [comment]
It isn't released even if the DialogHost is totally removed from the window.

Sep 23, 2024 4:31:06 PM SKProCH ***@***.***>:

**Comment by SKProCH** [comment]
As a workaround you can set the OverlayBackground and Background properties of DialogHost to some custom values (this prevents creating MultiDynamicResourceObservable). I've also would think about the solution, but since avalonia prohibit creating custom bindings this is isn't easy task.

**Comment by SKProCH** [comment]
Should be fixed with `v0.9.0-preview1`. If no - please, reopen the issue.
