### ISSUE TITLE
DialogHostStyle.CornerRadius do not work on SimpleTheme

### ISSUE THREAD

**Issue by xlxdd** [AvaloniaUtils/DialogHost.Avalonia#69]
DialogHostStyle.CornerRadius do not work on SimpleTheme.When I changed it into fluenttheme in app.axaml it works.
I notice that DialogHostStyle.CornerRadius `Works only for default DialogHost theme`,does it mean fluenttheme?

**Comment by SKProCH** [comment]
Hello, @xlxdd 

I've fixed bug in SimpleTheme.

As for 

> I notice that DialogHostStyle.CornerRadius Works only for default DialogHost theme,does it mean fluenttheme?

No, this means default *DialogHost theme* (and any application theme).  This is a TemplatedControl, so anyone can write your own styles for DialogHost and DialogOverlayPopupHost, and this properties can be unsupported there.

**Comment by SKProCH** [comment]
This version soon will be released as v0.9.0-preview2
