### ISSUE TITLE
Popup focus issues

### ISSUE THREAD

**Issue by danipen** [AvaloniaUtils/DialogHost.Avalonia#7]
I found a couple of issues:

1. The focus is drawn with some unwanted offset.
2. The focus should be restricted to the Popup.

https://user-images.githubusercontent.com/501613/162749424-1672cd29-0aae-4a4a-965d-00d0e3f0f69a.mp4

If someone gives me some clues about how to fix it, I can try to create a PR.

**Comment by danipen** [comment]
@SKProCH any ideas?

**Comment by SKProCH** [comment]
Hmm, this is strange. Can you provide project for testing?

**Comment by danipen** [comment]
@SKProCH the issue happens always. This example reproduces the issue.bhttps://github.com/danipen/SlowAnimationMinimalApp

**Comment by danipen** [comment]
I took a look and I was unable to find the issue. 😔

**Comment by danipen** [comment]
Hey @SKProCH something new about his?

**Comment by SKProCH** [comment]
Not yet. I could not find a quick solution, and could not spend more time because of work. I will try this weekend to figure it out and fix it.

**Comment by SKProCH** [comment]
@danipen you can install version v0.5.0-rc0 from nuget now.
It should fix your issue. If not - feel free to reopen it.

**Comment by danipen** [comment]
Thank you very much for taking a look. I'm out now I'll return next Thursday. I'll take a look then.

**Comment by SKProCH** [comment]
Hello, @danipen 
Were you able to check this bug?
